name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  terraform-provider-release:
    name: 'Brightbox Terraform Provider Release'
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-privat-key-passphrase: ${{ secrets.PASSPHRASE }}
    with:
      setup-go-version-file: 'go.mod'
